on:
  push:
    branches:
      - main
    pull_request:
      branches:
      - main
    workflow_dispatch: #adds button on github
     
jobs:
  hello:
    runs-on: ubuntu-linux
    steps:
      - uses: actions/checkout@v2
        run: echo "hello world"
        shell: bash
  bye:
    runs-on: ubuntu-linux
    steps:
      - uses: actions/checkout@v2
        run: echo "Bye Bye world"
        shell: bash